/**
 * Herdr Tab Name Extension
 *
 * Mirrors the pi session display name onto the herdr tab label via
 * `herdr tab rename <TAB_ID> <label>`. Renames only when a session name
 * exists: on session_start for resumed or already-named sessions, and on
 * session_info_changed (a manual /name, or a title generated by the
 * llm-session-name extension, which flows through setSessionName). A cleared
 * name never renames the tab.
 *
 * No-op outside herdr: HERDR_ENV must be "1" and HERDR_TAB_ID must be set.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";

/** Collapse whitespace runs and trim; used for tab labels. */
export const cleanLabel = (name: string): string => name.replace(/\s+/g, " ").trim();

export default function (pi: ExtensionAPI) {
	// Read at registration time: a pi process runs in one pane, so the env
	// context is fixed for the process lifetime. Checking here (not at module
	// scope) keeps the extension testable via process.env mutation.
	const tabId = process.env.HERDR_TAB_ID;
	if (process.env.HERDR_ENV !== "1" || !tabId) {
		return;
	}

	// Chain renames so rapid event bursts cannot interleave concurrent
	// `herdr tab rename` calls; the last label always wins.
	let inFlight: Promise<void> = Promise.resolve();

	const renameTab = (name: string) => {
		const label = cleanLabel(name);
		if (!label) return;
		inFlight = inFlight.then(
			() =>
				new Promise<void>((resolve) => {
					execFile("herdr", ["tab", "rename", tabId, label], () => {
						// Best-effort: a failed rename (no server, version drift)
						// must never surface as an unhandled error in pi.
						resolve();
					});
				}),
		);
	};

	pi.on("session_start", async () => {
		try {
			const name = pi.getSessionName();
			if (name) renameTab(name);
		} catch {
			// Best-effort.
		}
	});

	pi.on("session_info_changed", async (event) => {
		// Only a defined name renames the tab; a cleared name leaves it alone.
		if (typeof event.name === "string" && event.name) {
			renameTab(event.name);
		}
	});
}
