/**
 * Herdr Session Label Extension
 *
 * Mirrors the pi session display name onto herdr labels via
 * `herdr pane rename <PANE_ID> <label>` (always) and
 * `herdr tab rename <TAB_ID> <label>` (only when the tab has exactly one
 * pane, queried via `herdr tab get`). Renames fire on session_start for
 * resumed or already-named sessions and on session_info_changed (a manual
 * /name, or a title generated by the llm-session-name extension, which flows
 * through setSessionName).
 *
 * An unnamed session resets the labels instead of leaving stale ones: the
 * pane label is cleared (`herdr pane rename <PANE_ID> --clear`, restoring the
 * herdr default) and the single-pane tab label is set to the placeholder
 * "pi". Resets fire on session_start with reason "new", "resume", or "fork";
 * "startup" and "reload" are exempt so a plain pi launch never clobbers an
 * existing label. A name cleared via session_info_changed always resets.
 * Multi-pane tabs get no tab action: no single agent may claim a shared tab.
 *
 * Subagent child sessions spawned by @tintinweb/pi-subagents never touch
 * either surface: they run in the same pi process, inherit the herdr env,
 * and would otherwise overwrite the labels with their auto-assigned name
 * (e.g. "general#123455AB") for as long as they run. See isSubagentSession.
 *
 * No-op outside herdr: HERDR_ENV must be "1" and HERDR_TAB_ID and
 * HERDR_PANE_ID must be set.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";

/** Label a single-pane tab gets while its session has no name. */
export const UNNAMED_TAB_LABEL = "pi";

/** Collapse whitespace runs and trim; used for herdr labels. */
export const cleanLabel = (name: string): string => name.replace(/\s+/g, " ").trim();

/** Matches the pi-subagents child-session naming scheme: "type#<8-char id>". */
const SUBAGENT_NAME_PATTERN = /#[0-9A-Za-z_-]{8}$/;

/**
 * True for subagent child sessions spawned by @tintinweb/pi-subagents. Two
 * signals, either is sufficient: pi-subagents stamps a persisted child
 * session's header with parentSession (the spawner's session file), and it
 * names every child session "<type>#<first 8 chars of a nanoid id>" before
 * extensions bind. The name pattern also covers nested (in-memory) child
 * sessions, whose header carries no parentSession.
 */
export const isSubagentSession = (
	name: string,
	header?: { parentSession?: string } | null,
): boolean => !!header?.parentSession || SUBAGENT_NAME_PATTERN.test(name);

/**
 * True for session_start reasons that replace an existing session and may
 * leave a stale label behind. "startup" and "reload" are exempt: a plain pi
 * launch or extension reload must not clobber a label that was set outside
 * this extension.
 */
export const isResetReason = (reason: string): boolean =>
	reason === "new" || reason === "resume" || reason === "fork";

/** What to do with a label: rename to a label, clear it, or leave it alone. */
export type LabelAction = { kind: "rename"; label: string } | { kind: "clear" } | { kind: "none" };

/**
 * Pane-label decision for a session name. Subagent sessions are ignored;
 * a named session renames the pane; an unnamed session clears the pane
 * label (restoring herdr's default) so no stale title lingers.
 */
export const resolvePaneAction = (name: string | undefined, isSubagent: boolean): LabelAction => {
	if (isSubagent) return { kind: "none" };
	if (!name) return { kind: "clear" };
	return { kind: "rename", label: cleanLabel(name) };
};

/**
 * Tab-label decision for a session name and the tab's pane count. Subagent
 * sessions are ignored. Multi-pane tabs (and tabs whose pane count is
 * unknown, e.g. a failed `herdr tab get`) are left alone: no single agent
 * may claim a shared tab. An unnamed session in a single-pane tab gets the
 * fixed placeholder instead of a blank label (herdr renders an empty tab
 * label as nothing).
 */
export const resolveTabAction = (
	name: string | undefined,
	isSubagent: boolean,
	paneCount: number | undefined,
): { kind: "rename"; label: string } | { kind: "none" } => {
	if (isSubagent || paneCount !== 1) return { kind: "none" };
	if (!name) return { kind: "rename", label: UNNAMED_TAB_LABEL };
	return { kind: "rename", label: cleanLabel(name) };
};

/**
 * Read the session header off an event context, tolerating a missing context,
 * session manager, or getHeader method (older/mocked contexts). Returns
 * undefined when nothing usable is there, which counts as "not a subagent".
 */
const getHeader = (ctx: unknown): { parentSession?: string } | undefined => {
	try {
		const sessionManager = (ctx as { sessionManager?: { getHeader?: () => unknown } } | undefined)
			?.sessionManager;
		const header = sessionManager?.getHeader?.();
		if (header && typeof header === "object") return header as { parentSession?: string };
	} catch {
		// Best-effort: an unreadable header counts as "not a subagent".
	}
	return undefined;
};

/** Runs one `herdr` invocation, resolving with stdout. */
export type HerdrRun = (args: string[]) => Promise<string>;

const defaultRun: HerdrRun = (args) =>
	new Promise<string>((resolve, reject) => {
		execFile("herdr", args, (error, stdout) => {
			if (error) reject(error);
			else resolve(stdout);
		});
	});

export default function (pi: ExtensionAPI, deps?: { run?: HerdrRun }) {
	const run = deps?.run ?? defaultRun;
	// Read at registration time: a pi process runs in one pane, so the env
	// context is fixed for the process lifetime. Checking here (not at module
	// scope) keeps the extension testable via process.env mutation.
	const tabId = process.env.HERDR_TAB_ID;
	const paneId = process.env.HERDR_PANE_ID;
	if (process.env.HERDR_ENV !== "1" || !tabId || !paneId) {
		return;
	}

	// Chain every herdr invocation so rapid event bursts cannot interleave
	// concurrent CLI calls; the last label always wins.
	let inFlight: Promise<void> = Promise.resolve();

	const enqueue = (task: () => Promise<void>): void => {
		inFlight = inFlight.then(task).catch(() => {
			// Best-effort: a failed herdr call (no server, version drift) must
			// never surface as an unhandled error in pi.
		});
	};

	const renamePane = (label: string): void => {
		enqueue(() => run(["pane", "rename", paneId, label]).then(() => undefined));
	};

	const clearPane = (): void => {
		enqueue(() => run(["pane", "rename", paneId, "--clear"]).then(() => undefined));
	};

	/**
	 * Apply one pane action and, unless the pane is ignored (subagent), one
	 * tab action. The tab decision is re-evaluated inside the queued task
	 * against a fresh pane count: a tab that gained a pane between the event
	 * and the call must not be renamed by this agent.
	 */
	const applySessionName = (name: string | undefined, isSubagent: boolean): void => {
		const paneAction = resolvePaneAction(name, isSubagent);
		if (paneAction.kind === "rename") renamePane(paneAction.label);
		else if (paneAction.kind === "clear") clearPane();
		else return;

		enqueue(async () => {
			const count = await run(["tab", "get", tabId]).then(
				(stdout) => {
					const parsed = JSON.parse(stdout) as { result?: { tab?: { pane_count?: unknown } } };
					const value = parsed.result?.tab?.pane_count;
					return typeof value === "number" && Number.isInteger(value) ? value : undefined;
				},
				() => undefined,
			);
			const tabAction = resolveTabAction(name, isSubagent, count);
			if (tabAction.kind === "rename") {
				await run(["tab", "rename", tabId, tabAction.label]);
			}
		});
	};

	pi.on("session_start", async (event, ctx) => {
		try {
			const name = pi.getSessionName() ?? undefined;
			if (isSubagentSession(name ?? "", getHeader(ctx))) return;
			if (name) {
				applySessionName(name, false);
				return;
			}
			if (isResetReason(event.reason)) applySessionName(undefined, false);
		} catch {
			// Best-effort.
		}
	});

	pi.on("session_info_changed", async (event, ctx) => {
		try {
			const name = typeof event.name === "string" && event.name ? event.name : undefined;
			if (isSubagentSession(name ?? "", getHeader(ctx))) return;
			applySessionName(name, false);
		} catch {
			// Best-effort.
		}
	});
}
